[package]
name = "rusty676"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
tokio = {version = "1", features = ["full"]}
serde = "1.0"
toml = "0.5.0"
serde_derive = "1.0.144"