name:
  basic_auth

info:
  type: auth

request:
  method: POST
  path: /
  query_string: Null
  creds: [username, password]

response:
  type: 'regstr'
  part: 'headers'
  matchstr: 'Authorization'
  matchstatus: 'OK'
  condtion: 'and'